### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sedagormus89**
Thank youu :)

### CODE REVIEW

**Comment by orcudy** [comment]
Changed okay -- will merge

**Comment by orcudy** [comment]
Merging

**Comment by orcudy** [comment]
Just realized that the README.md file did actually update. The reason that it looks the same is due to the way that markdown works: This markdown treats multiple newlines as one newline!

**Comment by sedagormus89** [comment]
Ohh got it! Also, the changes we made were just adding spaces, maybe thats why shows only one. If we would write a new text for 3 lines, then it would show it all i guess. Would it?

**Pull request merged**
